#!/usr/bin/env bash
cd "$(dirname "$0")" || exit

# DS OTA Save Backups

# Configuration
NDS_ADDR="192.168.67.230:5000"
NDS_DIR="/roms/games/" # Directory on the NDS to scan
BACKUP_DIR="./backups" # Where to store backups locally

echo "[1/3] Downloading saves"
STAGING_DIR=$(mktemp -d)
echo "DEBUG: STAGING_DIR: $STAGING_DIR"
trap 'rm -rf "${STAGING_DIR}"' EXIT
wget --quiet --show-progress \
	--recursive -l1 --no-directories \
	--accept "*.sav" --ignore-case \
	--read-timeout=6 --tries=7 \
	-P "${STAGING_DIR}" \
	"ftp://${NDS_ADDR}${NDS_DIR}"

echo "[2/3] Saving updates"
TIMESTAMP=$(date +%Y-%m-%d_%H%M)
mkdir -p "${BACKUP_DIR}"
shopt -s nocaseglob nullglob
for FILE in "${STAGING_DIR}"/*.sav; do
	FILENAME=$(basename "${FILE}")
	LATEST_BACKUP=$(find "${BACKUP_DIR}" -maxdepth 1 -name "${FILENAME}.*" | sort | tail -n 1)

	# Guard: Skip if unchanged
	[[ -n "$LATEST_BACKUP" ]] && cmp -s "${FILE}" "${LATEST_BACKUP}" && continue

	echo " Archiving ${FILENAME}"
	mv "${FILE}" "${BACKUP_DIR}/${FILENAME}.${TIMESTAMP}"
	touch -d "${TIMESTAMP/_/ }" "${BACKUP_DIR}/${FILENAME}.${TIMESTAMP}"
done
shopt -u nocaseglob nullglob

echo "[3/3] Backup complete"
